TrajectoryPlannerROS:
  max_vel_x: 0.2
  min_vel_x: 0.1
  max_vel_theta: 1.0
  min_vel_theta: -1.0
  min_in_place_vel_theta: 0.2

  acc_lim_theta: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 0

  yaw_goal_tolerance: 0.05
  xy_goal_tolerance: 0.10

  holonomic_robot: false
